// run `node index.js` in the terminal
//https://links.mead.io/nodecourse

//const fs = require('fs')
//fs.writeFileSync('Test95.txt','This is generated by node.')
//fs.appendFileSync('Test95.txt','Test Creation')
//console.log('Hi Rahul')

const txt = require('./Test1.js');
const val1 = require('validator');
const chlk1 = require('chalk');
const msg = txt();
console.log(msg);
console.log(chlk1.green(val1.isEmail('abccom@test.com')));
console.log(chlk1.red(val1.isURL('testcom')));
